# Generated by Django 5.2.5 on 2025-08-21 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("topic", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AIinteraction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prompt", models.TextField(verbose_name="Подсказка")),
                ("response", models.TextField(verbose_name="Ответ")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="topic.topic",
                        verbose_name="Тематика",
                    ),
                ),
            ],
        ),
    ]
