# Generated by Django 5.2.5 on 2025-08-21 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Goal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Заголовок")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "is_completed",
                    models.BooleanField(default=False, verbose_name="Достигнут"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "deadline",
                    models.DateField(blank=True, null=True, verbose_name="Срок"),
                ),
            ],
            options={
                "verbose_name": "Цель",
                "verbose_name_plural": "Цели",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MentorReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rating", models.PositiveSmallIntegerField()),
                ("comment", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Оценка",
                "verbose_name_plural": "Оценки",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Session",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("schedulet_at", models.DateTimeField(verbose_name="Запланировано")),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(
                        default=30, verbose_name="Продолжительность"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("mentoring", "Mentoring"),
                            ("interview", "Interview"),
                        ],
                        default="mentoring",
                        max_length=20,
                        verbose_name="Тип сессии",
                    ),
                ),
                (
                    "is_completed",
                    models.BooleanField(default=False, verbose_name="Закончен"),
                ),
                (
                    "feedback",
                    models.TextField(blank=True, verbose_name="Обратная связь"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
            ],
            options={
                "verbose_name": "Сессия",
                "verbose_name_plural": "Сессий",
                "ordering": ["-created_at"],
            },
        ),
    ]
